version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=matrimony_dev_user
      - POSTGRES_PASSWORD=matrimony_pass
      - POSTGRES_DB=matrimony_dev

volumes:
  postgres_data:
