# Generated by Django 3.1 on 2020-08-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_type_profile_set', to='profile_management.bodytype'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='complexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexion_profile_set', to='profile_management.complexion'),
        ),
    ]
