# Generated by Django 3.1 on 2020-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_auto_20200816_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('s', 'Sent'), ('a', 'Accepted'), ('r', 'Rejected')], max_length=1),
        ),
    ]
