# Generated by Django 3.1 on 2020-08-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0003_auto_20200816_1029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('from_profile', 'to_profile')},
        ),
    ]
